#!/usr/bin/env bash
# ABOUTME: Build and deploy frontend to Firebase Hosting or Cloud Storage
# ABOUTME: Supports multiple deployment targets with environment configuration

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${SCRIPT_DIR}/../config.sh"
source "${SCRIPT_DIR}/../env.production.sh"

TARGET="${1:-firebase}"  # firebase or gcs

# Functions defined first
deploy_to_firebase() {
    local frontend_dir="$1"

    echo ""
    echo ">>> Deploying to Firebase Hosting..."

    # Check if firebase CLI is installed
    if ! command -v firebase &>/dev/null; then
        echo "Firebase CLI not found. Install with: npm install -g firebase-tools"
        exit 1
    fi

    # Create firebase.json if it doesn't exist
    if [[ ! -f "${frontend_dir}/firebase.json" ]]; then
        echo "Creating firebase.json..."
        cat > "${frontend_dir}/firebase.json" << 'FIREBASE_JSON'
{
  "hosting": {
    "public": "dist",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
    "headers": [
      {
        "source": "**/*.@(js|css)",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=31536000, immutable"
          }
        ]
      },
      {
        "source": "**/*.@(jpg|jpeg|gif|png|svg|webp|ico)",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=86400"
          }
        ]
      }
    ]
  }
}
FIREBASE_JSON
    fi

    # Deploy
    cd "${frontend_dir}"
    firebase deploy --only hosting --project "${VITE_FIREBASE_PROJECT_ID}"

    echo "https://${VITE_FIREBASE_PROJECT_ID}.web.app"
}

deploy_to_gcs() {
    local frontend_dir="$1"

    echo ""
    echo ">>> Deploying to Cloud Storage..."

    BUCKET_NAME="${GCP_PROJECT_ID}-frontend"

    # Create bucket if it doesn't exist
    if ! gsutil ls "gs://${BUCKET_NAME}" &>/dev/null; then
        echo "Creating bucket ${BUCKET_NAME}..."
        gsutil mb -l "${GCP_REGION}" "gs://${BUCKET_NAME}"

        # Enable website hosting
        gsutil web set -m index.html -e index.html "gs://${BUCKET_NAME}"

        # Make bucket public
        gsutil iam ch allUsers:objectViewer "gs://${BUCKET_NAME}"
    fi

    # Sync dist folder to bucket
    echo "Uploading files..."
    gsutil -m rsync -r -d "${frontend_dir}/dist" "gs://${BUCKET_NAME}"

    # Set cache headers for JS/CSS
    gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" \
        "gs://${BUCKET_NAME}/**/*.js" \
        "gs://${BUCKET_NAME}/**/*.css" 2>/dev/null || true

    # Set cache headers for HTML
    gsutil -m setmeta -h "Cache-Control:public, max-age=86400" \
        "gs://${BUCKET_NAME}/**/*.html" 2>/dev/null || true

    echo "https://storage.googleapis.com/${BUCKET_NAME}/index.html"
}

# Main script starts here
echo "=== Pierre Frontend - Build & Deploy ==="
echo "Target: ${TARGET}"
echo ""

# Get backend URL from Cloud Run (if deployed)
if gcloud run services describe "${SERVICE_NAME}" --region="${GCP_REGION}" &>/dev/null; then
    BACKEND_URL=$(gcloud run services describe "${SERVICE_NAME}" \
        --region="${GCP_REGION}" \
        --format="value(status.url)")
    echo "Backend URL: ${BACKEND_URL}"
else
    echo "WARNING: Backend not deployed yet. Deploy backend first."
    echo "Run: ./scripts/deploy.sh"
    exit 1
fi

# Frontend directory
FRONTEND_DIR="${PROJECT_ROOT}/frontend"
ENV_FILE="${FRONTEND_DIR}/.env.production"

echo ""
echo ">>> Creating frontend .env.production..."
cat > "${ENV_FILE}" << EOF
# Generated by deploy-frontend.sh at $(date -Iseconds)
# DO NOT COMMIT - this file contains deployment-specific values

# Backend API URL
VITE_API_BASE_URL=${BACKEND_URL}

# Firebase Configuration
VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
EOF

echo "Created ${ENV_FILE}"

# Build frontend
echo ""
echo ">>> Building frontend..."
cd "${FRONTEND_DIR}"

# Install dependencies if needed
if [[ ! -d node_modules ]]; then
    echo "Installing dependencies..."
    npm install
fi

# Build for production
npm run build

echo "Build complete. Output in ${FRONTEND_DIR}/dist/"

# Deploy based on target
case "${TARGET}" in
    firebase)
        FRONTEND_URL=$(deploy_to_firebase "${FRONTEND_DIR}")
        ;;
    gcs)
        FRONTEND_URL=$(deploy_to_gcs "${FRONTEND_DIR}")
        ;;
    *)
        echo "Unknown target: ${TARGET}"
        echo "Supported targets: firebase, gcs"
        exit 1
        ;;
esac

# Update backend FRONTEND_URL
echo ""
echo ">>> Updating backend FRONTEND_URL..."
gcloud run services update "${SERVICE_NAME}" \
    --region="${GCP_REGION}" \
    --set-env-vars="FRONTEND_URL=${FRONTEND_URL}" \
    --quiet

echo ""
echo "=== Frontend Deployment Complete ==="
echo ""
echo "Backend:  ${BACKEND_URL}"
echo "Frontend: ${FRONTEND_URL}"
