# Cloud Build Configuration for Pierre MCP Server
# Triggers on: git push to main branch (via GitHub integration)
# Actions: Build Docker image → Push to Artifact Registry → Deploy to Cloud Run

# Build timeout (max 60 minutes for Rust compilation)
timeout: 3600s

# Substitution variables (passed from trigger or command line)
substitutions:
  _REGION: us-central1
  _SERVICE_NAME: pierre-mcp-server
  _ENVIRONMENT: staging  # Override with --substitutions=_ENVIRONMENT=production
  _ARTIFACT_REGISTRY_REPO: pierre-mcp
  _GCP_PROJECT_ID: ${PROJECT_ID}

# Build steps
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '--tag=${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--tag=${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${_ENVIRONMENT}'
      - '--tag=${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'
      - '--cache-from=${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'
      - '--build-arg=BUILDKIT_INLINE_CACHE=1'
      - '--file=Dockerfile'
      - '.'
    timeout: 2400s  # 40 minutes for Rust build

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}'
    waitFor:
      - 'build-image'

  # Step 3: Deploy to Cloud Run (staging auto-deploy, production requires approval)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image=${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --tag=${_ENVIRONMENT}-${SHORT_SHA}
    waitFor:
      - 'push-image'

  # Step 4: Run database migrations (Cloud Run Job)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Database migrations are handled automatically by the application on startup"
        echo "SQLx migrations run on first container boot via src/database/mod.rs"
    waitFor:
      - 'deploy-cloud-run'

  # Step 5: Smoke test the deployed service
  - name: 'gcr.io/cloud-builders/curl'
    id: 'smoke-test'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Get the Cloud Run service URL
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        echo "Testing health endpoint: $SERVICE_URL/health"

        # Wait for service to be ready (max 60 seconds)
        for i in {1..12}; do
          if curl -f -s "$SERVICE_URL/health" | grep -q "ok"; then
            echo "✅ Health check passed!"
            exit 0
          fi
          echo "⏳ Waiting for service to be ready... ($i/12)"
          sleep 5
        done

        echo "❌ Health check failed after 60 seconds"
        exit 1
    waitFor:
      - 'run-migrations'

# Images to store in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${_ENVIRONMENT}'
  - '${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'

# Cloud Build options
options:
  machineType: 'E2_HIGHCPU_8'  # Use high-CPU machine for faster Rust builds
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON

# IAM permissions required for Cloud Build service account:
# - roles/run.admin (deploy Cloud Run services)
# - roles/iam.serviceAccountUser (act as Cloud Run service account)
# - roles/artifactregistry.writer (push images)
# - roles/cloudbuild.builds.builder (default)
