name: Database Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/database**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/database**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  sqlite-tests:
    name: Database Tests (SQLite)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-sqlite-${{ hashFiles('**/Cargo.lock') }}

    - name: Run database plugin tests (SQLite)
      run: cargo test database_plugins_test --verbose
      env:
        DATABASE_URL: "sqlite::memory:"
        ENCRYPTION_KEY: "dGVzdF9lbmNyeXB0aW9uX2tleV9mb3JfY2lfb25seV8zMg=="
        RUST_LOG: "info"

    - name: Run integration tests (SQLite)
      run: cargo test --test oauth_integration --test api_key_integration_test --verbose
      env:
        DATABASE_URL: "sqlite::memory:"
        ENCRYPTION_KEY: "dGVzdF9lbmNyeXB0aW9uX2tleV9mb3JfY2lfb25seV8zMg=="
        RUST_LOG: "debug"

  postgresql-tests:
    name: Database Tests (PostgreSQL)
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: pierre
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: pierre_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-postgresql-${{ hashFiles('**/Cargo.lock') }}

    - name: Wait for PostgreSQL
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        timeout 60 bash -c 'until pg_isready -h localhost -p 5432 -U pierre; do sleep 2; done'
        echo "PostgreSQL is ready!"

    - name: Test database connection
      run: |
        PGPASSWORD=test_password psql -h localhost -U pierre -d pierre_test -c "SELECT 'PostgreSQL connection successful';"

    - name: Run database plugin tests (PostgreSQL)
      run: cargo test --features postgresql database_plugins_test --verbose -- --test-threads=1
      env:
        DATABASE_URL: "postgresql://pierre:test_password@localhost:5432/pierre_test"
        ENCRYPTION_KEY: "dGVzdF9lbmNyeXB0aW9uX2tleV9mb3JfY2lfb25seV8zMg=="
        RUST_LOG: "info"

    - name: Run integration tests (PostgreSQL)
      run: cargo test --features postgresql --test oauth_integration --test api_key_integration_test --verbose -- --test-threads=1
      env:
        DATABASE_URL: "postgresql://pierre:test_password@localhost:5432/pierre_test"
        ENCRYPTION_KEY: "dGVzdF9lbmNyeXB0aW9uX2tleV9mb3JfY2lfb25seV8zMg=="
        RUST_LOG: "debug"